"use client";

import { PageHero, Panel, StatGrid } from "@/components/page-kit";
import { Area, AreaChart, Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid, Legend, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar } from "recharts";
import { Activity, Zap, Clock, Wrench, ShieldCheck } from "lucide-react";
import { useState } from "react";

const proposalsData = [
  { sprint: "Sprint 1", proposals: 12, accepted: 4, rejected: 8 },
  { sprint: "Sprint 2", proposals: 18, accepted: 6, rejected: 12 },
  { sprint: "Sprint 3", proposals: 15, accepted: 7, rejected: 8 },
  { sprint: "Sprint 4", proposals: 22, accepted: 10, rejected: 12 },
  { sprint: "Sprint 5", proposals: 24, accepted: 11, rejected: 13 },
];

const fitnessScores = [
  { subject: "Efficiency", score: 85, fullMark: 100 },
  { subject: "Cost", score: 92, fullMark: 100 },
  { subject: "Reliability", score: 78, fullMark: 100 },
  { subject: "Speed", score: 88, fullMark: 100 },
  { subject: "Security", score: 95, fullMark: 100 },
];

const cyclicEfficiencyData = [
  { cycle: 1, time: 120 },
  { cycle: 2, time: 110 },
  { cycle: 3, time: 95 },
  { cycle: 4, time: 80 },
  { cycle: 5, time: 65 },
  { cycle: 6, time: 50 },
  { cycle: 7, time: 42 },
  { cycle: 8, time: 38 },
];

const workflowOptimizationData = [
  { workflow: "Data Prep", before: 45, after: 12 },
  { workflow: "Code Review", before: 60, after: 15 },
  { workflow: "Content Gen", before: 30, after: 5 },
  { workflow: "Report", before: 120, after: 20 },
];

export default function EvolutionPage() {
  const [kanban] = useState([
    { id: 1, title: "Web Scraper v2", status: "Testing", assignee: "Synth", priority: "High" },
    { id: 2, title: "Auto-Debugger", status: "Coding", assignee: "Synth", priority: "Critical" },
    { id: 3, title: "Log Parser", status: "Pending", assignee: "Darwin", priority: "Medium" },
    { id: 4, title: "SEO Analyzer", status: "Deploy", assignee: "Automata", priority: "High" },
  ]);

  return (
    <main className="mx-auto max-w-[1680px] pb-8">
      <PageHero
        eyebrow="Tier 6 • Evolution Department"
        title="Self-Improvement & Tooling"
        subtitle="Autonomous tool creation, workflow optimization, and systemic adaptation by Darwin, Synth, and Automata."
      />
      <StatGrid
        stats={[
          { label: "Automation ROI", value: "3,240h", trend: "saved this month", tone: "good", icon: <Clock size={20} /> },
          { label: "Systemic Adaptation", value: "4.2m", trend: "avg resolution", tone: "good", icon: <Zap size={20} /> },
          { label: "Active Tools", value: "42", tone: "default", icon: <Wrench size={20} /> },
          { label: "Regression Risk", value: "Low", tone: "good", icon: <ShieldCheck size={20} /> },
        ]}
      />

      <section className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-12">
        {/* Tool Success Rate Gauge */}
        <Panel title="Synth Tool Success Rate" subtitle="Error-free execution of generated code" className="xl:col-span-4">
          <div className="h-[300px] w-full mt-4 flex flex-col items-center justify-center">
            <div className="relative flex items-center justify-center">
              <svg className="w-48 h-24" viewBox="0 0 100 50">
                <path d="M 10 50 A 40 40 0 0 1 90 50" fill="none" stroke="hsl(var(--border))" strokeWidth="12" strokeLinecap="round" />
                <path d="M 10 50 A 40 40 0 0 1 90 50" fill="none" stroke="hsl(var(--chart-5))" strokeWidth="12" strokeLinecap="round" strokeDasharray="125" strokeDashoffset="10" className="transition-all duration-1000" />
              </svg>
              <div className="absolute bottom-0 flex flex-col items-center">
                <span className="text-3xl font-bold text-white">94%</span>
                <span className="text-xs text-sky-400 uppercase tracking-wider mt-1">Stable Tools</span>
              </div>
            </div>
            <div className="mt-8 text-center text-xs text-muted-foreground max-w-[200px]">
              Tools generated by Synth that pass all shadow tests and run without exceptions.
            </div>
          </div>
        </Panel>

        {/* Cyclic Efficiency */}
        <Panel title="Cyclic Efficiency Trend" subtitle="Execution time decrease across loops" className="xl:col-span-8">
          <div className="h-[300px] w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={cyclicEfficiencyData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorTime" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="hsl(var(--chart-1))" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="hsl(var(--chart-1))" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                <XAxis dataKey="cycle" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(v) => `C${v}`} />
                <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '12px', color: 'hsl(var(--foreground))' }}
                />
                <Legend iconType="circle" wrapperStyle={{ fontSize: '12px' }} />
                <Area type="monotone" dataKey="time" name="Execution Time (s)" stroke="hsl(var(--chart-1))" strokeWidth={3} fillOpacity={1} fill="url(#colorTime)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </Panel>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-12">
        {/* Workflow Optimization */}
        <Panel title="Automata Workflow Optimization" subtitle="Time saved by rewriting execution paths" className="xl:col-span-6">
          <div className="h-[300px] w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={workflowOptimizationData} layout="vertical" margin={{ top: 10, right: 30, left: 20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" horizontal={false} />
                <XAxis type="number" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis dataKey="workflow" type="category" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '12px', color: 'hsl(var(--foreground))' }}
                  cursor={{ fill: 'hsl(var(--border))', opacity: 0.4 }}
                />
                <Legend iconType="circle" wrapperStyle={{ fontSize: '12px' }} />
                <Bar dataKey="before" name="Before (mins)" fill="hsl(var(--muted-foreground))" radius={[0, 4, 4, 0]} />
                <Bar dataKey="after" name="Optimized (mins)" fill="#8b5cf6" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        {/* Shadow Testing Panel */}
        <Panel title="Shadow Testing Chamber" subtitle="Tools executing in dry-run mode" className="xl:col-span-6">
          <div className="h-[300px] overflow-y-auto pr-2 scrollbar-hide mt-4 space-y-3">
            {[
              { tool: "Market Scraper v3", metric: "Latency", target: "< 2s", current: "1.8s", status: "Passing" },
              { tool: "Auto-Triage Model", metric: "Accuracy", target: "> 95%", current: "92%", status: "Failing" },
              { tool: "Cost Optimizer", metric: "Savings", target: "> 10%", current: "12%", status: "Passing" },
              { tool: "DB Indexer", metric: "Query Speed", target: "2x faster", current: "2.5x", status: "Passing" },
            ].map((test, i) => (
              <div key={i} className="flex items-center justify-between p-4 rounded-xl bg-black/20 border border-white/5">
                <div className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <Activity size={14} className={test.status === 'Passing' ? 'text-emerald-400' : 'text-rose-400'} />
                    <span className="text-sm font-semibold text-white">{test.tool}</span>
                  </div>
                  <span className="text-xs text-muted-foreground">{test.metric}: Target {test.target}</span>
                </div>
                <div className="text-right flex flex-col gap-1">
                  <span className={`text-lg font-bold ${test.status === 'Passing' ? 'text-emerald-400' : 'text-rose-400'}`}>
                    {test.current}
                  </span>
                  <span className="text-[10px] text-muted-foreground uppercase tracking-wider">{test.status}</span>
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-12">
        <Panel title="Tool Factory Kanban" subtitle="Darwin requests to Synth" className="xl:col-span-12">
          <div className="mt-4 grid grid-cols-1 md:grid-cols-4 gap-4">
            {["Pending", "Coding", "Testing", "Deploy"].map(status => (
              <div key={status} className="rounded-xl border border-white/5 bg-black/20 p-4">
                <h3 className="text-sm font-semibold text-white/80 mb-3 flex items-center justify-between">
                  {status}
                  <span className="bg-white/10 text-white/60 text-xs px-2 py-0.5 rounded-full">
                    {kanban.filter(k => k.status === status).length}
                  </span>
                </h3>
                <div className="space-y-3">
                  {kanban.filter(k => k.status === status).map(item => (
                    <div key={item.id} className="rounded-lg border border-white/5 bg-white/5 p-3 hover:border-white/10 transition-colors">
                      <div className="flex justify-between items-start mb-2">
                        <span className={`text-[10px] uppercase font-bold tracking-wider px-1.5 py-0.5 rounded ${
                          item.priority === 'Critical' ? 'bg-rose-500/20 text-rose-400' : 
                          item.priority === 'High' ? 'bg-amber-500/20 text-amber-400' : 
                          'bg-white/10 text-white/60'
                        }`}>
                          {item.priority}
                        </span>
                        <span className="text-[10px] text-cyber-cyan border border-cyber-cyan/20 bg-cyber-cyan/10 px-1.5 py-0.5 rounded">
                          {item.assignee}
                        </span>
                      </div>
                      <p className="text-sm text-white font-medium">{item.title}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
        <Panel title="Proposals Timeline" subtitle="Aceitação de propostas por Sprint">
          <div className="h-[300px] w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={proposalsData} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                <XAxis dataKey="sprint" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '12px', color: 'hsl(var(--foreground))' }}
                  itemStyle={{ color: 'hsl(var(--foreground))' }}
                  cursor={{ fill: 'hsl(var(--border))', opacity: 0.4 }}
                />
                <Legend iconType="circle" wrapperStyle={{ fontSize: '12px' }} />
                <Bar dataKey="accepted" name="Accepted" fill="hsl(var(--chart-1))" radius={[0, 0, 4, 4]} stackId="a" />
                <Bar dataKey="rejected" name="Rejected" fill="hsl(var(--destructive))" radius={[4, 4, 0, 0]} stackId="a" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel title="Darwin Analysis" subtitle="Fitness score da estratégia atual">
          <div className="h-[300px] w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="80%" data={fitnessScores}>
                <PolarGrid stroke="hsl(var(--border))" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 12 }} />
                <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                <Radar name="Current Strategy" dataKey="score" stroke="hsl(var(--primary))" fill="hsl(var(--primary))" fillOpacity={0.4} />
                <Tooltip 
                  contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '12px', color: 'hsl(var(--foreground))' }}
                  itemStyle={{ color: 'hsl(var(--foreground))' }}
                />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </Panel>
      </section>
    </main>
  );
}



